CREATE TABLE `school_detail` (
  `address` varchar(255) DEFAULT NULL,
  `admissions` int(11) DEFAULT NULL,
  `school` varchar(255) DEFAULT NULL,
  `belong` varchar(255) DEFAULT NULL,
  `central` int(11) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `city_name` varchar(255) DEFAULT NULL,
  `code_enroll` int(11) DEFAULT NULL,
  `county_id` int(11) DEFAULT NULL,
  `county_name` varchar(255) DEFAULT NULL,
  `data_code` varchar(50) DEFAULT NULL,
  `department` int(11) DEFAULT NULL,
  `dual_class` int(11) DEFAULT NULL,
  `dual_class_name` varchar(255) DEFAULT NULL,
  `f211` int(11) DEFAULT NULL,
  `f985` int(11) DEFAULT NULL,
  `id` varchar(50) DEFAULT NULL,
  `is_recruitment` int(5) DEFAULT NULL,
  `is_top` int(2) DEFAULT NULL,
  `keywords` varchar(255) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `level_name` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `province_id` int(11) DEFAULT NULL,
  `province_name` varchar(255) DEFAULT NULL,
  `rank` int(11) DEFAULT NULL,
  `rank_type` int(11) DEFAULT NULL,
  `school_id` int(11) NOT NULL,
  `school_type` int(11) DEFAULT NULL,
  `type` int(11) DEFAULT NULL,
  `type_name` varchar(255) DEFAULT NULL,
  `view_month` int(11) DEFAULT NULL,
  `view_total` varchar(50) DEFAULT NULL,
  `_version_` int(11) DEFAULT NULL,
  PRIMARY KEY (`school_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `school_gk` (
  `average` decimal(8,2) DEFAULT NULL,
  `batch` int(11) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `level1` int(11) DEFAULT NULL,
  `level1_name` varchar(10) DEFAULT NULL,
  `level2` int(11) DEFAULT NULL,
  `level2_name` varchar(50) DEFAULT NULL,
  `level3` int(11) DEFAULT NULL,
  `level3_name` varchar(50) DEFAULT NULL,
  `local_batch_name` varchar(50) DEFAULT NULL,
  `max` decimal(8,2) DEFAULT NULL,
  `min` decimal(8,2) DEFAULT NULL,
  `min_section` int(11) DEFAULT NULL,
  `province` int(11) DEFAULT NULL,
  `remark` varchar(50) DEFAULT NULL,
  `school_id` int(11) DEFAULT NULL,
  `special_id` int(11) DEFAULT NULL,
  `spid` int(11) DEFAULT NULL,
  `spname` varchar(50) DEFAULT NULL,
  `type` int(11) DEFAULT NULL,
  `year` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `special` (`batch`,`province`,`school_id`,`special_id`,`spid`,`type`,`year`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8